/**
 * Figma Token Patch API Route
 *
 * Generated by `inkbridge setup`. Do not move this file.
 * The Figma plugin calls POST /api/inkbridge/patch-tokens during Push to Code
 * to apply token updates. Two request shapes:
 *
 *   { cssText, updatesByTheme }     → { patchedCss }        (PostCSS AST patcher)
 *   { themeSource, updatesByTheme } → { patchedTheme, applied, skipped }
 *                                     (MUI theme.ts ts-morph patcher)
 *
 * The MUI patcher runs as a `tsx` subprocess reaching into the inkbridge
 * package — the same mechanism the scan route uses for the scanner CLI
 * (Next.js does not transpile TypeScript inside node_modules).
 *
 * Types are deliberately explicit (no implicit `any` from `request.json()`
 * or property access on unknown payloads) so this file passes consumer
 * projects that enable strict `@typescript-eslint/no-explicit-any` /
 * `no-unsafe-*` rules without needing per-file eslint-disable comments.
 *
 * To re-generate: pnpm exec inkbridge setup
 */

import { NextResponse } from 'next/server';
import postcss, { type AtRule, type Rule, type Declaration, type Container } from 'postcss';
import * as path from 'path';
import * as fs from 'fs';
import { spawnSync } from 'child_process';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

const CWD = process.cwd();
const TSX = path.resolve(CWD, 'node_modules/.bin/tsx');
// `INKBRIDGE_LOCAL=1` points at a sibling inkbridge checkout — same hot-loop
// escape hatch as the scan route (see scan-components-route.ts).
const LOCAL_PATCHER_CLI = path.resolve(
  CWD, '..', 'inkbridge', 'tools', 'figma-plugin', 'scanner', 'mui', 'mui-theme-patcher-cli.ts'
);
const PATCHER_CLI = process.env.INKBRIDGE_LOCAL === '1' && fs.existsSync(LOCAL_PATCHER_CLI)
  ? LOCAL_PATCHER_CLI
  : path.resolve(CWD, 'node_modules/inkbridge/scanner/mui/mui-theme-patcher-cli.ts');

type ThemeUpdateMap = Record<string, Record<string, string>>;
type PatchPayload = { cssText?: unknown; themeSource?: unknown; updatesByTheme?: unknown };

type ThemePatchResult = {
  patched: string;
  applied: string[];
  skipped: { key: string; reason: string }[];
};

function isThemePatchResult(value: unknown): value is ThemePatchResult {
  if (!value || typeof value !== 'object') return false;
  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.patched === 'string' &&
    Array.isArray(candidate.applied) &&
    Array.isArray(candidate.skipped)
  );
}

function patchMuiThemeViaCli(themeSource: string, updatesByTheme: ThemeUpdateMap): ThemePatchResult {
  const result = spawnSync(TSX, [PATCHER_CLI], {
    cwd: CWD,
    encoding: 'utf-8',
    input: JSON.stringify({ themeSource, updatesByTheme }),
  });
  // Forward subprocess stderr to the dev server's terminal, same as the
  // scan route — patcher diagnostics stay visible without extra plumbing.
  if (result.stderr) process.stderr.write(result.stderr);
  if (result.status !== 0) {
    throw new Error(result.stderr || 'MUI theme patcher exited with non-zero status');
  }
  const parsed: unknown = JSON.parse(result.stdout || 'null');
  if (!isThemePatchResult(parsed)) {
    throw new Error('MUI theme patcher returned an unexpected shape');
  }
  return parsed;
}

function isThemeUpdateMap(value: unknown): value is ThemeUpdateMap {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  for (const inner of Object.values(value as Record<string, unknown>)) {
    if (!inner || typeof inner !== 'object' || Array.isArray(inner)) return false;
    for (const v of Object.values(inner as Record<string, unknown>)) {
      if (typeof v !== 'string') return false;
    }
  }
  return true;
}

function parseThemeSelectors(selector: string): string[] {
  const themes = new Set<string>();
  const normalized = String(selector || '').trim().toLowerCase();
  if (!normalized) return [];

  const matches = normalized.matchAll(/\[data-theme\s*=\s*["']?([^"'\\\]]+)["']?\]/g);
  for (const match of matches) {
    const themeName = String(match[1] || '').trim();
    if (themeName) themes.add(themeName);
  }

  if (/(\.|:)(dark)\b/.test(normalized)) themes.add('dark');
  if (normalized.includes(':root') && themes.size === 0) themes.add('primary');
  return Array.from(themes);
}

function cloneUpdates(updatesByTheme: ThemeUpdateMap): Map<string, Map<string, string>> {
  const out = new Map<string, Map<string, string>>();
  for (const [themeName, updates] of Object.entries(updatesByTheme || {})) {
    const normalizedTheme = String(themeName || '').trim().toLowerCase();
    if (!normalizedTheme) continue;
    if (!updates || typeof updates !== 'object') continue;
    const map = out.get(normalizedTheme) || new Map<string, string>();
    for (const [prop, value] of Object.entries(updates)) {
      if (!prop || !prop.startsWith('--')) continue;
      map.set(prop, String(value));
    }
    if (map.size > 0) out.set(normalizedTheme, map);
  }
  return out;
}

function resolveThemesForNode(node: Rule | AtRule): string[] {
  if (node.type === 'atrule') {
    return String((node as AtRule).name || '').toLowerCase() === 'theme' ? ['primary'] : [];
  }
  const selectors = Array.isArray((node as Rule).selectors)
    ? (node as Rule).selectors
    : String((node as Rule).selector || '').split(',');
  const themes = new Set<string>();
  for (const selector of selectors) {
    for (const themeName of parseThemeSelectors(selector)) {
      themes.add(themeName);
    }
  }
  return Array.from(themes);
}

function walkTokenContainers(root: postcss.Root): Array<Rule | AtRule> {
  const containers: Array<Rule | AtRule> = [];
  root.walk((node) => {
    if (node.type !== 'rule' && node.type !== 'atrule') return;
    const typed = node as Rule | AtRule;
    const themes = resolveThemesForNode(typed);
    if (themes.length > 0) containers.push(typed);
  });
  return containers;
}

function appendDecl(container: Rule | AtRule, prop: string, value: string): void {
  const decl = postcss.decl({ prop, value });
  if (!container.nodes || container.nodes.length === 0) {
    decl.raws.before = '\n  ';
  } else {
    const sample = container.nodes.find((n) => n.type === 'decl') as Declaration | undefined;
    decl.raws.before = sample?.raws?.before || '\n  ';
  }
  (container as unknown as Container).append(decl);
}

function patchCssVariables(cssText: string, updatesByTheme: ThemeUpdateMap): string {
  const root = postcss.parse(cssText);
  const pending = cloneUpdates(updatesByTheme);
  const containers = walkTokenContainers(root);

  for (const container of containers) {
    const themes = resolveThemesForNode(container);
    if (themes.length === 0) continue;

    for (const themeName of themes) {
      const updates = pending.get(String(themeName || '').toLowerCase());
      if (!updates || updates.size === 0) continue;

      for (const node of container.nodes || []) {
        if (node.type !== 'decl') continue;
        const decl = node as Declaration;
        if (!decl.prop || !updates.has(decl.prop)) continue;
        decl.value = String(updates.get(decl.prop) || '');
        updates.delete(decl.prop);
      }
    }
  }

  for (const [themeName, updates] of pending.entries()) {
    if (updates.size === 0) continue;

    let target: Rule | AtRule | null = null;
    for (const container of containers) {
      const themes = resolveThemesForNode(container);
      if (themes.includes(themeName)) {
        target = container;
        break;
      }
    }

    // Do not create missing theme blocks from sparse updates here.
    // The plugin runtime performs the authoritative second pass that
    // handles stale-theme pruning and full-theme block insertion.
    if (!target) continue;

    for (const [prop, value] of updates.entries()) {
      appendDecl(target, prop, value);
    }
  }

  return root.toString();
}

export async function POST(request: Request): Promise<NextResponse> {
  // Production guard. The Figma plugin only ever calls this on localhost
  // during design work. Exposing the route on a deployed app gains
  // nothing but adds a DoS vector (postcss-parses arbitrary `cssText`,
  // CORS `*`, no auth). Returning 404 (rather than 403) makes the route
  // indistinguishable from a missing endpoint — no signal to attackers
  // that something is here.
  if (process.env.NODE_ENV === 'production') {
    return new NextResponse(null, { status: 404 });
  }
  try {
    const payload = (await request.json()) as PatchPayload;
    const cssText = typeof payload.cssText === 'string' ? payload.cssText : '';
    const themeSource = typeof payload.themeSource === 'string' ? payload.themeSource : '';
    const updatesByTheme: ThemeUpdateMap = isThemeUpdateMap(payload.updatesByTheme)
      ? payload.updatesByTheme
      : {};

    // MUI shape: patch the consumer's theme.ts source via the ts-morph
    // patcher inside the inkbridge package (tsx subprocess).
    if (themeSource) {
      const result = patchMuiThemeViaCli(themeSource, updatesByTheme);
      return NextResponse.json(
        { patchedTheme: result.patched, applied: result.applied, skipped: result.skipped },
        { headers: CORS }
      );
    }

    if (!cssText) {
      return NextResponse.json(
        { error: 'Invalid payload: cssText or themeSource is required.' },
        { status: 400, headers: CORS }
      );
    }

    const patchedCss = patchCssVariables(cssText, updatesByTheme);
    return NextResponse.json({ patchedCss }, { headers: CORS });
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to patch CSS tokens', message: error instanceof Error ? error.message : String(error) },
      { status: 500, headers: CORS }
    );
  }
}

export async function OPTIONS(): Promise<NextResponse> {
  if (process.env.NODE_ENV === 'production') {
    return new NextResponse(null, { status: 404 });
  }
  return new NextResponse(null, { headers: CORS });
}
