import type { Meta, StoryObj } from "@storybook/react";
import { IncreasePositionModal } from "./IncreasePositionModal";

const meta = {
  title: "Feature/Perps/IncreasePositionModal",
  component: IncreasePositionModal,
  parameters: {
    layout: "padded",
  },
} satisfies Meta<typeof IncreasePositionModal>;

export default meta;
type Story = StoryObj<typeof meta>;

// IncreasePositionModal is presentational — every value comes from
// runtime state in production. Stories inline literals so the Inkbridge
// plugin scanner reads them without modelling React state.

const USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
const USDT_MINT = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB";

const PREVIEW_METRICS = {
  tokenMeta: { symbol: "SOL", decimals: 9 },
  sideLabel: "Long",
  accentClass: "text-emerald-600",
  quoteSide: "long" as const,
  deltaTokenDisplay: "1.4500",
  totalTokenDisplay: "1.4500",
  deltaUsdDisplay: "$250.00",
  totalUsdDisplay: "$250.00",
  entryBeforeDisplay: null,
  entryAfterDisplay: "$172.41",
  markPriceDisplay: "$172.41",
  liquidationBeforeDisplay: null,
  liquidationAfterDisplay: "$138.92",
  slippageActualDisplay: "0.12 %",
  maxSlippageDisplay: "1 %",
  openFeeUsdDisplay: "$0.25",
  openFeePercentDisplay: "0.10 %",
  priceImpactUsdDisplay: "$0.05",
  priceImpactPercentDisplay: "0.02 %",
  borrowFeesUsdDisplay: "$0.00",
  totalFeesUsdDisplay: "$0.30",
  txFeeDisplay: "$0.0001",
  rentDisplay: null,
};

export const OpenLong: Story = {
  args: {
    open: true,
    mode: "open",
    marketSymbol: "SOL",
    hasLongPosition: false,
    hasShortPosition: false,
    form: {
      side: "long",
      collateralAmount: "100",
      sizeUsd: "",
      leverage: "5",
      maxSlippagePercent: "1",
      inputMint: USDC_MINT,
    },
    onFormChange: () => undefined,
    allowedInputMints: [USDC_MINT, USDT_MINT],
    collateralGuidance: null,
    balancesLoading: false,
    inputWalletBalance: 1250.5,
    isLongSide: true,
    defaultLeverage: 5,
    leverageMarks: ["1x", "5x", "10x", "25x", "50x"],
    maxLeverage: 50,
    sizeUsdPreview: 500,
    collateralLimitsError: null,
    status: null,
    loading: false,
    previewLoading: false,
    previewMetrics: PREVIEW_METRICS,
    previewError: null,
    connected: true,
    onSubmit: () => undefined,
    onClose: () => undefined,
    onOpenChange: () => undefined,
  },
};

export const OpenShort: Story = {
  args: {
    open: true,
    mode: "open",
    marketSymbol: "SOL",
    hasLongPosition: false,
    hasShortPosition: false,
    form: {
      side: "short",
      collateralAmount: "150",
      sizeUsd: "",
      leverage: "10",
      maxSlippagePercent: "1",
      inputMint: USDC_MINT,
    },
    onFormChange: () => undefined,
    allowedInputMints: [USDC_MINT, USDT_MINT],
    collateralGuidance: null,
    balancesLoading: false,
    inputWalletBalance: 1250.5,
    isLongSide: false,
    defaultLeverage: 10,
    leverageMarks: ["1x", "5x", "10x", "25x", "50x"],
    maxLeverage: 50,
    sizeUsdPreview: 1500,
    collateralLimitsError: null,
    status: null,
    loading: false,
    previewLoading: false,
    previewMetrics: {
      ...PREVIEW_METRICS,
      sideLabel: "Short",
      accentClass: "text-rose-600",
      quoteSide: "short",
      deltaTokenDisplay: "8.6900",
      totalTokenDisplay: "8.6900",
      deltaUsdDisplay: "$1,500.00",
      totalUsdDisplay: "$1,500.00",
      liquidationAfterDisplay: "$206.89",
      openFeeUsdDisplay: "$1.50",
      totalFeesUsdDisplay: "$1.55",
    },
    previewError: null,
    connected: true,
    onSubmit: () => undefined,
    onClose: () => undefined,
    onOpenChange: () => undefined,
  },
};

export const IncreaseExistingLong: Story = {
  args: {
    open: true,
    mode: "increase",
    marketSymbol: "SOL",
    hasLongPosition: true,
    hasShortPosition: false,
    form: {
      side: "long",
      collateralAmount: "200",
      sizeUsd: "",
      leverage: "5",
      maxSlippagePercent: "1",
      inputMint: USDC_MINT,
    },
    onFormChange: () => undefined,
    allowedInputMints: [USDC_MINT, USDT_MINT],
    collateralGuidance: "Increasing long exposure to existing position.",
    balancesLoading: false,
    inputWalletBalance: 2500,
    isLongSide: true,
    defaultLeverage: 5,
    leverageMarks: ["1x", "5x", "10x", "25x", "50x"],
    maxLeverage: 50,
    sizeUsdPreview: 1000,
    collateralLimitsError: null,
    status: null,
    loading: false,
    previewLoading: false,
    previewMetrics: {
      ...PREVIEW_METRICS,
      deltaTokenDisplay: "5.8000",
      totalTokenDisplay: "7.2500",
      deltaUsdDisplay: "$1,000.00",
      totalUsdDisplay: "$1,250.00",
      entryBeforeDisplay: "$170.20",
      entryAfterDisplay: "$172.07",
      liquidationBeforeDisplay: "$140.50",
      liquidationAfterDisplay: "$138.92",
      openFeeUsdDisplay: "$1.00",
      totalFeesUsdDisplay: "$1.05",
    },
    previewError: null,
    connected: true,
    onSubmit: () => undefined,
    onClose: () => undefined,
    onOpenChange: () => undefined,
  },
};

export const InsufficientBalance: Story = {
  args: {
    open: true,
    mode: "open",
    marketSymbol: "SOL",
    hasLongPosition: false,
    hasShortPosition: false,
    form: {
      side: "long",
      collateralAmount: "5000",
      sizeUsd: "",
      leverage: "5",
      maxSlippagePercent: "1",
      inputMint: USDC_MINT,
    },
    onFormChange: () => undefined,
    allowedInputMints: [USDC_MINT, USDT_MINT],
    collateralGuidance: null,
    balancesLoading: false,
    inputWalletBalance: 250,
    isLongSide: true,
    defaultLeverage: 5,
    leverageMarks: ["1x", "5x", "10x", "25x", "50x"],
    maxLeverage: 50,
    sizeUsdPreview: null,
    collateralLimitsError: null,
    status: null,
    loading: false,
    previewLoading: false,
    previewMetrics: null,
    previewError: null,
    connected: true,
    onSubmit: () => undefined,
    onClose: () => undefined,
    onOpenChange: () => undefined,
  },
};

export const PreviewLoading: Story = {
  args: {
    open: true,
    mode: "open",
    marketSymbol: "SOL",
    hasLongPosition: false,
    hasShortPosition: false,
    form: {
      side: "long",
      collateralAmount: "100",
      sizeUsd: "",
      leverage: "5",
      maxSlippagePercent: "1",
      inputMint: USDC_MINT,
    },
    onFormChange: () => undefined,
    allowedInputMints: [USDC_MINT, USDT_MINT],
    collateralGuidance: null,
    balancesLoading: false,
    inputWalletBalance: 1250.5,
    isLongSide: true,
    defaultLeverage: 5,
    leverageMarks: ["1x", "5x", "10x", "25x", "50x"],
    maxLeverage: 50,
    sizeUsdPreview: 500,
    collateralLimitsError: null,
    status: null,
    loading: false,
    previewLoading: true,
    previewMetrics: null,
    previewError: null,
    connected: true,
    onSubmit: () => undefined,
    onClose: () => undefined,
    onOpenChange: () => undefined,
  },
};

export const Disconnected: Story = {
  args: {
    open: true,
    mode: "open",
    marketSymbol: "SOL",
    hasLongPosition: false,
    hasShortPosition: false,
    form: {
      side: "long",
      collateralAmount: "",
      sizeUsd: "",
      leverage: "5",
      maxSlippagePercent: "1",
      inputMint: USDC_MINT,
    },
    onFormChange: () => undefined,
    allowedInputMints: [USDC_MINT, USDT_MINT],
    collateralGuidance: null,
    balancesLoading: false,
    inputWalletBalance: null,
    isLongSide: true,
    defaultLeverage: 5,
    leverageMarks: ["1x", "5x", "10x", "25x", "50x"],
    maxLeverage: 50,
    sizeUsdPreview: null,
    collateralLimitsError: null,
    status: null,
    loading: false,
    previewLoading: false,
    previewMetrics: null,
    previewError: null,
    connected: false,
    onSubmit: () => undefined,
    onClose: () => undefined,
    onOpenChange: () => undefined,
  },
};
