/**
 * Figma Token Patch API Route
 *
 * Generated by `inkhouse setup`. Do not move this file.
 * The Figma plugin calls POST /api/figma/patch-tokens during Push to Code
 * to apply token updates via a PostCSS AST patcher.
 *
 * To re-generate: pnpm exec inkhouse setup
 */

import { NextResponse } from 'next/server';
import postcss, { type AtRule, type Rule, type Declaration, type Container } from 'postcss';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

type ThemeUpdateMap = Record<string, Record<string, string>>;

function parseThemeSelectors(selector: string): string[] {
  const themes = new Set<string>();
  const normalized = String(selector || '').trim().toLowerCase();
  if (!normalized) return [];

  const matches = normalized.matchAll(/\[data-theme\s*=\s*["']?([^"'\\\]]+)["']?\]/g);
  for (const match of matches) {
    const themeName = String(match[1] || '').trim();
    if (themeName) themes.add(themeName);
  }

  if (/(\.|:)(dark)\b/.test(normalized)) themes.add('dark');
  if (normalized.includes(':root') && themes.size === 0) themes.add('primary');
  return Array.from(themes);
}

function cloneUpdates(updatesByTheme: ThemeUpdateMap): Map<string, Map<string, string>> {
  const out = new Map<string, Map<string, string>>();
  for (const [themeName, updates] of Object.entries(updatesByTheme || {})) {
    const normalizedTheme = String(themeName || '').trim().toLowerCase();
    if (!normalizedTheme) continue;
    if (!updates || typeof updates !== 'object') continue;
    const map = out.get(normalizedTheme) || new Map<string, string>();
    for (const [prop, value] of Object.entries(updates)) {
      if (!prop || !prop.startsWith('--')) continue;
      map.set(prop, String(value));
    }
    if (map.size > 0) out.set(normalizedTheme, map);
  }
  return out;
}

function resolveThemesForNode(node: Rule | AtRule): string[] {
  if (node.type === 'atrule') {
    return String((node as AtRule).name || '').toLowerCase() === 'theme' ? ['primary'] : [];
  }
  const selectors = Array.isArray((node as Rule).selectors)
    ? (node as Rule).selectors
    : String((node as Rule).selector || '').split(',');
  const themes = new Set<string>();
  for (const selector of selectors) {
    for (const themeName of parseThemeSelectors(selector)) {
      themes.add(themeName);
    }
  }
  return Array.from(themes);
}

function walkTokenContainers(root: postcss.Root): Array<Rule | AtRule> {
  const containers: Array<Rule | AtRule> = [];
  root.walk((node) => {
    if (node.type !== 'rule' && node.type !== 'atrule') return;
    const typed = node as Rule | AtRule;
    const themes = resolveThemesForNode(typed);
    if (themes.length > 0) containers.push(typed);
  });
  return containers;
}

function appendDecl(container: Rule | AtRule, prop: string, value: string): void {
  const decl = postcss.decl({ prop, value });
  if (!container.nodes || container.nodes.length === 0) {
    decl.raws.before = '\n  ';
  } else {
    const sample = container.nodes.find((n) => n.type === 'decl') as Declaration | undefined;
    decl.raws.before = sample?.raws?.before || '\n  ';
  }
  (container as unknown as Container).append(decl);
}

function patchCssVariables(cssText: string, updatesByTheme: ThemeUpdateMap): string {
  const root = postcss.parse(cssText);
  const pending = cloneUpdates(updatesByTheme);
  const containers = walkTokenContainers(root);

  for (const container of containers) {
    const themes = resolveThemesForNode(container);
    if (themes.length === 0) continue;

    for (const themeName of themes) {
      const updates = pending.get(String(themeName || '').toLowerCase());
      if (!updates || updates.size === 0) continue;

      for (const node of container.nodes || []) {
        if (node.type !== 'decl') continue;
        const decl = node as Declaration;
        if (!decl.prop || !updates.has(decl.prop)) continue;
        decl.value = String(updates.get(decl.prop) || '');
        updates.delete(decl.prop);
      }
    }
  }

  for (const [themeName, updates] of pending.entries()) {
    if (updates.size === 0) continue;

    let target: Rule | AtRule | null = null;
    for (const container of containers) {
      const themes = resolveThemesForNode(container);
      if (themes.includes(themeName)) {
        target = container;
        break;
      }
    }

    // Do not create missing theme blocks from sparse updates here.
    // The plugin runtime performs the authoritative second pass that
    // handles stale-theme pruning and full-theme block insertion.
    if (!target) continue;

    for (const [prop, value] of updates.entries()) {
      appendDecl(target, prop, value);
    }
  }

  return root.toString();
}

export async function POST(request: Request) {
  try {
    const payload = await request.json();
    const cssText = typeof payload?.cssText === 'string' ? payload.cssText : '';
    const updatesByTheme = (payload?.updatesByTheme || {}) as ThemeUpdateMap;

    if (!cssText) {
      return NextResponse.json(
        { error: 'Invalid payload: cssText is required.' },
        { status: 400, headers: CORS }
      );
    }

    const patchedCss = patchCssVariables(cssText, updatesByTheme);
    return NextResponse.json({ patchedCss }, { headers: CORS });
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to patch CSS tokens', message: error instanceof Error ? error.message : String(error) },
      { status: 500, headers: CORS }
    );
  }
}

export async function OPTIONS() {
  return new NextResponse(null, { headers: CORS });
}
