/**
 * Figma Component Scanner API Route
 *
 * Generated by `inkbridge setup`. Do not move this file.
 * The Figma plugin calls GET /api/figma/scan-components when the user
 * clicks "Generate Design System Page".
 *
 * To re-generate: pnpm exec inkbridge setup
 */

import { NextResponse } from 'next/server';
import * as path from 'path';
import * as fs from 'fs';
import { spawnSync } from 'child_process';

const CWD = process.cwd();
const TSX = path.resolve(CWD, 'node_modules/.bin/tsx');
const CLI = path.resolve(CWD, 'node_modules/inkbridge/scanner/cli.ts');
const OUTPUT = path.resolve(CWD, '.inkbridge/component-definitions.json');

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

export async function GET(request: Request) {
  try {
    const url = new URL(request.url);
    const tokenSourceMode = url.searchParams.get('tokenSourceMode') || 'auto';
    const cssTokenPath = url.searchParams.get('cssTokenPath') || undefined;
    const dtcgTokenPath = url.searchParams.get('dtcgTokenPath') || undefined;

    fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });

    const args = [CLI, '--output', OUTPUT, '--include-tokens', '--token-mode', tokenSourceMode];
    if (cssTokenPath) args.push('--css-token-path', cssTokenPath);
    if (dtcgTokenPath) args.push('--dtcg-token-path', dtcgTokenPath);

    const result = spawnSync(TSX, args, { cwd: CWD, encoding: 'utf-8' });
    if (result.status !== 0) {
      throw new Error(result.stderr || 'Scanner exited with non-zero status');
    }

    const output = JSON.parse(fs.readFileSync(OUTPUT, 'utf-8'));
    return NextResponse.json(output, { headers: CORS });
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to scan components', message: error instanceof Error ? error.message : String(error) },
      { status: 500, headers: CORS }
    );
  }
}

export async function OPTIONS() {
  return new NextResponse(null, { headers: CORS });
}
